### ISSUE TITLE
startup.sh runs without errors, tomcat started, getting blank screen on localhost:8090

### ISSUE THREAD

**Issue by sashamitrovich** [ryanjdew/discovery-app-w-samplestack#7]
```
...
rver/java-spring/static/index.html
10:26:28.017 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Root mapping to handler of type [class org.springframework.web.servlet.mvc.ParameterizableViewController]
10:26:28.028 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:26:28.028 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:26:28.046 [main] INFO  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Detected @ExceptionHandler methods in exceptionAdvice
10:26:28.061 [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
10:26:28.206 [Finalizer] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
10:26:28.395 [main] INFO  o.s.b.a.s.AuthenticationManagerConfiguration - 

Using default security password: 97443434-db2b-4b6d-a62c-1665c37f54d5

10:26:28.404 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
10:26:28.415 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8090"]
10:26:28.420 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8090"]
10:26:28.421 [main] INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
10:26:28.439 [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8090 (http)
10:26:28.441 [main] INFO  c.marklogic.samplestack.Application - Started Application in 7.303 seconds (JVM running for 7.739)
10:26:37.511 [http-nio-8090-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
10:26:37.511 [http-nio-8090-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
10:26:37.523 [http-nio-8090-exec-1] INFO  o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms
> Building 80% > :bootRun
```

**Comment by sashamitrovich** [comment]
and the javascript console message:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngJsonExplorer due to:
Error: [$injector:nomod] Module 'ngJsonExplorer' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=ngJsonExplorer
    at http://localhost:8090/deps/angular/angular.js:63:12
    at http://localhost:8090/deps/angular/angular.js:1764:17
    at ensure (http://localhost:8090/deps/angular/angular.js:1688:38)
    at module (http://localhost:8090/deps/angular/angular.js:1762:14)
    at http://localhost:8090/deps/angular/angular.js:4094:22
    at forEach (http://localhost:8090/deps/angular/angular.js:323:20)
    at loadModules (http://localhost:8090/deps/angular/angular.js:4078:5)
    at http://localhost:8090/deps/angular/angular.js:4095:40
    at forEach (http://localhost:8090/deps/angular/angular.js:323:20)
    at loadModules (http://localhost:8090/deps/angular/angular.js:4078:5)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=ngJsonExplorer&p1=E…%20(http%3A%2F%2Flocalhost%3A8090%2Fdeps%2Fangular%2Fangular.js%3A4078%3A5)
    at http://localhost:8090/deps/angular/angular.js:63:12
    at http://localhost:8090/deps/angular/angular.js:4117:15
    at forEach (http://localhost:8090/deps/angular/angular.js:323:20)
    at loadModules (http://localhost:8090/deps/angular/angular.js:4078:5)
    at http://localhost:8090/deps/angular/angular.js:4095:40
    at forEach (http://localhost:8090/deps/angular/angular.js:323:20)
    at loadModules (http://localhost:8090/deps/angular/angular.js:4078:5)
    at createInjector (http://localhost:8090/deps/angular/angular.js:4004:11)
    at doBootstrap (http://localhost:8090/deps/angular/angular.js:1446:20)
    at Object.bootstrap (http://localhost:8090/deps/angular/angular.js:1467:12)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=app&p1=Error%3A%20%…20(http%3A%2F%2Flocalhost%3A8090%2Fdeps%2Fangular%2Fangular.js%3A1467%3A12)
```
